import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavigationBar/NavBar";
import { ProgressBarLayout } from "@/components/Common/process-bar";
import Footer from "@/components/Footer/Footer";
import ReduxProvider from "@/hooks/redux-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>JobCenter</title>
      <body>
        <div className="relative z-50">
          <NavBar />
        </div>
        <ReduxProvider>
          <ProgressBarLayout>{children}</ProgressBarLayout>
        </ReduxProvider>
        <Footer />
      </body>
    </html>
  );
}
